-- SQL Create script generated by spatialite gui from an existing geopackage cat_code_llid_ps
-- Geopackage is located in RStudio/spawn_survey_data/data

CREATE TABLE "cat_code_llid_ps.gpkg" (
   "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   "geom" MULTILINESTRING,
   "StreamCatalogID" TEXT,
   "LLID" TEXT,
   "LLID_StreamName" TEXT,
   "GNIS_StreamName" TEXT,
   "TributaryToLLID" TEXT,
   "Shape_Length" REAL,
   "wria_code" TEXT,
   "wria_name" TEXT)
